name: tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled
      - review_requested
      - reopened
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ========== Set up JDK 17 ==========
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: ========== Set up mysql testing database ==========
        uses: mirromutth/mysql-action@v1.1
        with:
#          host port: 3800 # Optional, default value is 3306. The port of host
#          container port: 3307 # Optional, default value is 3306. The port of container
#          character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
#          collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: '4156dbtest' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'dbuserdbuser' # Required if "mysql user" is empty, default is empty. The root superuser password
          mysql user: 'testuser' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
          mysql password: 'dbuserdbuser' # Required if "mysql user" exists. The password for the "mysql user"

      - name: ========== Cache the Maven packages to speed up build ==========
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: ========== Running Tests And Generate Report ==========
        run: mvn verify
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 85
      - name: Get the Coverage info
        run: |
          echo "Total coverage ${{ steps.jacoco.outputs.coverage-overall }}"
          echo "Changed Files coverage ${{ steps.jacoco.outputs.coverage-changed-files }}"
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Commit and push the badge (if it changed)
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'commit badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco/
      - name: Fail PR if overall coverage is less than 85%
        if: ${{ steps.jacoco.outputs.coverage-overall < 85.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 85%!')
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: SonarCloud analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=easymoney
      - name: Create comment in PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{github.event.number}}
          body: |
            SonarQube Scan Report: https://sonarcloud.io/dashboard?id=easymoney&pullRequest=${{github.event.number}}
      - name: Add markdown to summary
        uses: LouisBrunner/checks-action@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: SonarQube Scan
          conclusion: https://sonarcloud.io/dashboard?id=easymoney&pullRequest=${{github.event.number}}
          output: https://sonarcloud.io/dashboard?id=easymoney&pullRequest=${{github.event.number}}
